# Generated by Django 3.1.7 on 2022-03-07 09:31

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('anne', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cluster_name', models.CharField(max_length=200)),
                ('cluster_desc', models.CharField(max_length=200)),
                ('cluster_hashtags', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anne.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_video', embed_video.fields.EmbedVideoField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anne.cluster')),
            ],
        ),
    ]
